wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.23
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.0
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.0
      5: 0.10.23
      8:
      - 5
